### Schedule a flight
POST http://localhost:8080/api/flight-scheduler/schedule
Content-Type: application/json
Accept: application/json

{
  "departure": "SAEZ",
  "destination": "EBAW",
  "flightNumber": "AR1235",
  "departureTime": "2022-12-12T12:00:00Z",
  "arrivalTime": "2022-12-12T18:00:00-05:00"
}

### Retrieve a scheduled flight
GET http://localhost:8080/api/flight-scheduler/schedule/bfe6774a-9003-4730-888a-c012bc08ffec
Accept: application/json

### Retrieve all scheduled flights
GET http://localhost:8080/api/flight-scheduler/schedule
Accept: application/json

### Retrieve all scheduled flights by flightNumber
GET http://localhost:8080/api/flight-scheduler/schedule/search?flightNumber=AR1235
Accept: application/json

### Cancel a scheduled flight
DELETE http://localhost:8080/api/flight-scheduler/schedule/bfe6774a-9003-4730-888a-c012bc08ffec

